optim:
  lr: 1e-5
  lr_schedule: warmup_linear #warmup_linear,warmup_constant
  weight_decay: 0.01
  max_grad_norm: 0.0
  adam_b1: 0.9
  adam_b2: 0.98
  adam_eps: 1e-6
  adam_correct_bias: True
  warmup_proportion: 0.06
  gradient_accumulation_steps: 1

train:
  gradient_accumulation_steps: 3
  num_train_epochs: 2
